[project]
name = "li_4yp"
version = "0.1.1"
description = "Hair shade prediction experiments"
authors = [
    { name = "Boting Li" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pandas",
    "Pillow",
    "PyYAML",
    "scikit-learn",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
